sudo: required

language: generic

services:
- docker

script:
- ./build-docker.sh
- ls -lahR deploy
- "[ -s deploy/*.zip ]"

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true
